server:
  port: 8081

spring:
  application:
    name: "user-service"
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:15432/ecommerce_user
    username: postgres
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET:iqe7Fa7xrhXwJ5SLoee88Yg7DeUuJflj4+IE/XIl81tmZ24qNd4tCUble1Zk2drO=}
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 86400000

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "https://pposiraegi.cloud"