# [Stage 1: Build]
FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app

# 모듈 이름을 인자로 받음 (예: api-gateway, user-service)
ARG MODULE_NAME
ENV MODULE_NAME=${MODULE_NAME}

# Gradle Wrapper 및 설정 파일 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

# 모든 모듈의 build.gradle 복사
COPY api-gateway/build.gradle api-gateway/
COPY common/common-core/build.gradle common/common-core/
COPY common/common-jpa/build.gradle common/common-jpa/
COPY common/common-web-mvc/build.gradle common/common-web-mvc/
COPY grpc-interface/build.gradle grpc-interface/
COPY order-service/build.gradle order-service/
COPY product-service/build.gradle product-service/
COPY user-service/build.gradle user-service/

# 공통 모듈 소스 복사
COPY common/common-core/src common/common-core/src
COPY common/common-jpa/src common/common-jpa/src
COPY common/common-web-mvc/src common/common-web-mvc/src

COPY grpc-interface/src grpc-interface/src

# 대상 모듈 소스만 복사
COPY ${MODULE_NAME}/src ${MODULE_NAME}/src

RUN chmod +x gradlew
# 해당 모듈만 빌드
RUN ./gradlew :${MODULE_NAME}:bootJar -x test

# [Stage 2: Run]
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

ARG MODULE_NAME
ENV MODULE_NAME=${MODULE_NAME}

# 빌드된 대상 모듈의 jar만 복사
COPY --from=build /app/${MODULE_NAME}/build/libs/*.jar app.jar

ENV JAVA_OPTS="-Xms512m -Xmx512m -Duser.timezone=Asia/Seoul -Djava.security.egd=file:/dev/./urandom"
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
