spring:
  application:
    name: "order-service"
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:15432/ecommerce_order
    username: postgres
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 16379
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 64
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      channels:
        user-service:
          address: ${USER_GRPC_URL:static://user-service:9090}
          negotiation-type: plaintext
        product-service:
          address: ${PRODUCT_GRPC_URL:static://product-service:9090}
          negotiation-type: plaintext


cors:
  allowed-origins:
    - "http://localhost:3000"
    - "https://pposiraegi.cloud"

pg:
  success-url: http://localhost:8083/api/v1/orders/success
  fail-url: http://localhost:8083/api/v1/orders/fail