spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/ecommerce
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 64
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms

pg:
  success-url: https://pposiraegi.cloud/api/v1/orders/success
  fail-url: https://pposiraegi.cloud/api/v1/orders/fail
