apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: pposiraegi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::779846782353:role/pposiraegi-order-service-irsa
