apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: pposiraegi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::779846782353:role/pposiraegi-product-service-irsa
