spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "https://pposiraegi.cloud"
                  - "https://www.pposiraegi.cloud"
                  - "${CORS_ALLOWED_ORIGINS}"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true
