spring:
  application:
    name: "PPosiraegi-Backend"
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:15432/ecommerce
    username: postgres
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100 # N+1 Problem
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 16379
      #      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 64
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms

  threads:
    virtual:
      enabled: true

  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduler-

jwt:
  secret: ${JWT_SECRET:iqe7Fa7xrhXwJ5SLoee88Yg7DeUuJflj4+IE/XIl81tmZ24qNd4tCUble1Zk2drO=}
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 86400000

storage:
  location: C:/tmp/pposiraegi/uploads/images

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "https://pposiraegi.cloud"

pg:
  success-url: http://localhost:8080/api/v1/orders/success
  fail-url: http://localhost:8080/api/v1/orders/fail